### ISSUE TITLE
Indexing is failing

### ISSUE THREAD

**Issue by cmpich** [alliance-genome/agr#124]
I ran the indexer on my aws dev site with the following error:

Deleting mapping...
Traceback (most recent call last):
  File "fetch_save_index.py", line 109, in <module>
    fetch_save_index.load_data_from_sources_and_index()
  File "fetch_save_index.py", line 55, in load_data_from_sources_and_index
    self.delete_mapping()
  File "fetch_save_index.py", line 71, in delete_mapping
    response = requests.delete(os.environ['ES_URI'] + os.environ['ES_INDEX'] + "/")
  File "/home/cpich/.virtualenvs/agr_prototype/local/lib/python2.7/site-packages/requests/api.py", line 148, in delete
    return request('delete', url, **kwargs)
  File "/home/cpich/.virtualenvs/agr_prototype/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/cpich/.virtualenvs/agr_prototype/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cpich/.virtualenvs/agr_prototype/local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/cpich/.virtualenvs/agr_prototype/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9200): Max retries exceeded with url: /searchable_items_blue/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f5e383d2590>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by cmpich** [comment]
I guess I need an ES instance to hook up?

**Comment by oblodgett** [comment]
Yes you can download es from:
https://www.elastic.co/downloads/elasticsearch

Once you extract the tar file go into the elasticsearch-5.2.1/bin directory and run ./elasticsearch and it will start up a search running on 127.0.0.1:9200

**Comment by christabone** [comment]
Can this be closed @cmpich ?

**Comment by cmpich** [comment]
Yes, I installed latest ES and now it's working.
Would be nice to have the version we are using sitting in a shared location so other people only have to copy it into their directory.
