### ISSUE TITLE
Python3 compat

### ISSUE THREAD

**Issue by mgrbyte** [alliance-genome/agr#24]
build and tests fail.

I will work on a patch that attempts to make it work on both 2 and 3.

**Comment by mgrbyte** [comment]
Example error under Python3:
```======================================================================
ERROR: test_search_returns_json_object (test_search.SearchEndpointsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matt/.virtualenvs/agr-prototype/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/matt/git/agr_prototype/test/integration_tests/test_search.py", line 287, in test_search_returns_json_object
    data = json.loads(response.data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```

**Comment by christabone** [comment]
Migration to Python 3 is not currently possible with the Intermine libraries. Hopefully soon.
