### ISSUE TITLE
fielddata=true problem in Elasticsearch 5

### ISSUE THREAD

**Issue by jogoodma** [alliance-genome/agr#75]
I ran into this issue when working with the ES 5 image under docker.

```
api_1  | Traceback (most recent call last):
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
api_1  |     return self.wsgi_app(environ, start_response)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
api_1  |     response = self.make_response(self.handle_exception(e))
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
api_1  |     reraise(exc_type, exc_value, tb)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
api_1  |     response = self.full_dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
api_1  |     rv = self.handle_user_exception(e)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
api_1  |     reraise(exc_type, exc_value, tb)
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
api_1  |     rv = self.dispatch_request()
api_1  |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
api_1  |     return self.view_functions[rule.endpoint](**req.view_args)
api_1  |   File "/usr/src/app/src/server.py", line 118, in search
api_1  |     body=aggregation_body
api_1  |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
api_1  |     return func(*args, params=params, **kwargs)
api_1  |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 548, in search
api_1  |     doc_type, '_search'), params=params, body=body)
api_1  |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
api_1  |     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
api_1  |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
api_1  |     self._raise_error(response.status, raw_data)
api_1  |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
api_1  |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
api_1  | RequestError: TransportError(400, u'search_phase_execution_exception', u'Fielddata is disabled on text fields by default. Set fielddata=true on [category] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.')
```
It looks like a new config option in 5 that needs to be set when creating the index.

I'm rolling back to ES 2 until someone can dig further into this.

**Comment by kevinschaper** [comment]
I've looked into this a little, but haven't been able to get a working fix.

The mapping needs to change per:
https://www.elastic.co/blog/strings-are-dead-long-live-strings

I made changes that possibly satisfied that, but then ran into "filtered" being deprecated also:
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/query-dsl-filtered-query.html

Here's my mapping commit/branch, for what that's worth:
https://github.com/kevinschaper/agr_prototype/commit/01eace73cd631108b102eefae5f32e5f4934b507
